use `id9282948_scc`;
-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 16:13:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ativo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(100) NULL,
  `tombo` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `tombo_UNIQUE` (`tombo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chamado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chamado` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `usuario_atribuido` INT UNSIGNED NOT NULL,
  `ativo_atribuido` INT UNSIGNED NOT NULL,
  `data_abertura` TIMESTAMP NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`, `usuario_atribuido`, `ativo_atribuido`),
  INDEX `fk_chamado_usuario_idx` (`usuario_atribuido` ASC),
  INDEX `fk_chamado_ativo1_idx` (`ativo_atribuido` ASC),
  CONSTRAINT `fk_chamado_usuario`
    FOREIGN KEY (`usuario_atribuido`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chamado_ativo1`
    FOREIGN KEY (`ativo_atribuido`)
    REFERENCES `ativo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
